### ISSUE TITLE
recompile due to gitbucket binary incompatibility

### ISSUE THREAD

**Issue by McFoggy** [yoshiyoshifujii/gitbucket-desktopnotify-plugin#3]
due to gitbucket/gitbucket#1088, the project needs to be recompiled and release

**Comment by yoshiyoshifujii** [comment]
commit at https://github.com/yoshiyoshifujii/gitbucket-desktopnotify-plugin/commit/17cae34cbb739e74ac417b039a54b1a6696331fb
