### ISSUE TITLE
compatibility with gitbucket 4.10

### ISSUE THREAD

**Issue by McFoggy** [yoshiyoshifujii/gitbucket-desktopnotify-plugin#7]
Please consider to adapt to gitbucket 4.10, see [release notes](https://gitbucket.github.io/gitbucket-news/gitbucket/2017/02/25/gitbucket-4.10.html)

**Comment by yoshiyoshifujii** [comment]
adapt to gitbucket 4.10.
https://github.com/yoshiyoshifujii/gitbucket-desktopnotify-plugin/releases/tag/4.10.0

**Comment by aadrian** [comment]
@yoshiyoshifujii  Could you please update and release it to the latest version?  See: https://github.com/yoshiyoshifujii/gitbucket-desktopnotify-plugin/pull/9

Thank you.

**Comment by yoshiyoshifujii** [comment]
https://github.com/yoshiyoshifujii/gitbucket-desktopnotify-plugin/releases/tag/4.32.0
